### PR TITLE
Fixes topAnchor calculation to respect minimumTopDistance

### LINKED ISSUE #78: minTopDistance not working
I set min top distance and it doesnt seem to take effect. Xcode 12.0 beta 4. I can set the other properties of the style however and they work

### PR DESCRIPTION
**Pull request by styrken**
Fixes #78

### CODE REVIEW

File: Sources/PartialSheet/PartialSheetViewModifier.swift [hunk 1]
```diff
@@ -32,13 +32,18 @@ struct PartialSheet: ViewModifier {
...
             (UIApplication.shared.windows.first?.safeAreaInsets.bottom ?? 0) -
-            sheetContentRect.height - handlerSectionHeight,
-                   style.minTopDistance)
+            sheetContentRect.height - handlerSectionHeight
+        
+        if calculatedTop > self.style.minTopDistance {
+            return calculatedTop
+        }
+        
+        return self.style.minTopDistance
```
Comment (AndreaMiotto) [inline Sources/PartialSheet/PartialSheetViewModifier.swift:46]:
```
let calculatedTop = presenterContentRect.height +
              (UIApplication.shared.windows.first?.safeAreaInsets.bottom ?? 0) -		              (UIApplication.shared.windows.first?.safeAreaInsets.bottom ?? 0) -
              sheetContentRect.height - handlerSectionHeight,		              sheetContentRect.height - handlerSectionHeight
                     style.minTopDistance)		 
if calculatedTop > self.style.minTopDistance {
              return calculatedTop
          }
 
return self.style.minTopDistance
```

Can we change the if with a guard?
Is the self really needed?

**Review by AndreaMiotto — CHANGES_REQUESTED** [review]

File: Sources/PartialSheet/PartialSheetViewModifier.swift (hunk 1 above)
Comment (styrken) [reply Sources/PartialSheet/PartialSheetViewModifier.swift:46]: Sure, we can change it.

```self``` is there to express scope but I am not religious about it :-) I will update the PR

**Review by AndreaMiotto — APPROVED** [review]
